### ISSUE TITLE
Update to SDN5 / SD Kay

### ISSUE THREAD

**Issue by jexp** [neo4j-examples/movies-kotlin-spring-data-neo4j-4#1]
@jasperblues after the SF 5.0 SDN5.0 SD2.0 release next week, could you update this project too?

**Comment by jasperblues** [comment]
Sure

**Comment by meistermeier** [comment]
Hi @jasperblues. Has there been any work started on your side? Otherwise I can help and update it.

**Comment by jasperblues** [comment]
Hello @meistermeier. Not yet, unfortunately. If you're interested in helping that would be great.

**Comment by jasperblues** [comment]
@meistermeier Let me know if you work on it, ok? Otherwise I have some time on Sunday and Monday :)

**Comment by meistermeier** [comment]
That sounds great. I do not want to put stress on you ;) I think I won't accomplish this today but also have a look back here on Monday. So we can sync again if you have not started then.

**Comment by jasperblues** [comment]
@meistermeier Have at least built against a more recent Kotlin. Will come back to SDN5 asap.

**Comment by jasperblues** [comment]
@meistermeier conversion to SDN5 in progress

**Comment by jasperblues** [comment]
@meistermeier I updated to SDN5, however on the following: 

```kotlin
@RelationshipEntity(type = "ACTED_IN")
class Role(@GraphId var id: Long? = null,
           @StartNode var person: Person,
           @EndNode var movie: Movie,
           var roles: ArrayList<String> = ArrayList()) {

    fun addRoleName(name: String) {
        this.roles.add(name)
    }

```

Changing `@GraphId` to `@Id` here causes breakages. Let's explore why - will post on the #ogm slack channel, and raise an issue if required. 

https://github.com/neo4j-examples/movies-kotlin-spring-data-neo4j/blob/master/src/main/java/movies/spring/data/neo4j/domain/model/persistent/entities/Role.kt

**Comment by meistermeier** [comment]
As mentioned on slack before:
If `@Id` is used and its value gets not set manually `@GeneratedValue` must also be added to the field, to make use of the `InternalIdStrategy`.
Thanks for your update.

**Comment by jasperblues** [comment]
Thanks @meistermeier. Update to SDN5 is complete - please can close this off whenever you're happy.
